
    fun main() {
        val a1=Alumno("Pedro","Garcia Mora",1)
        val a2=Alumno("Marco","Mora Garrido",1)
        val a3=Alumno("Ana","Garcia Garcia",1)
        val a4=Alumno("Antonio","Gracia Mora",1)
        val a5=Alumno("Pablo","Mora Morales",1)
        val a6=Alumno("Javi","Morales Morales",1)
        val a7=Alumno("Alberto","Gallego Cepero",1)
        val a8=Alumno("Rosa","Cepero Morales",1)
        val a9=Alumno("Isabel","Cepero Mora",1)
        val a10=Alumno("Monica","Garcia Cepero",1)
        var m1=Modulo(15,3)
        m1.matriculaAlumno(a1)
        m1.rellenaNotas(3,m1.numAlumno)
        m1.matriculaAlumno(a2)
        m1.rellenaNotas(3,m1.numAlumno)
        m1.matriculaAlumno(a3)
        m1.rellenaNotas(3,m1.numAlumno)
        m1.matriculaAlumno(a4)
        m1.rellenaNotas(3,m1.numAlumno)
        m1.matriculaAlumno(a5)
        m1.rellenaNotas(3,m1.numAlumno)
        m1.matriculaAlumno(a6)
        m1.rellenaNotas(3,m1.numAlumno)
        m1.matriculaAlumno(a7)
        m1.rellenaNotas(3,m1.numAlumno)
        m1.matriculaAlumno(a8)
        m1.rellenaNotas(3,m1.numAlumno)
        m1.matriculaAlumno(a9)
        m1.rellenaNotas(3,m1.numAlumno)
        m1.matriculaAlumno(a10)
        m1.rellenaNotas(3,m1.numAlumno)


    }
